version: '3.8'

services:
    db:
        image: mysql
        container_name: db
        volumes:
            - ./\.db/:/var/lib/mysql
        restart: always
        cap_add:
            - SYS_NICE
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wp:
        image: wordpress
        container_name: wp
        volumes:
            - ./:/var/www/html

            # Disable cache and increase file size limits at the same time
            - ./php-config.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
        depends_on:
            - db
        ports:
            - 80:80
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DEBUG: 1
            WORDPRESS_TABLE_PREFIX: www_
