version: '3'

services:
  db:
    image: mariadb
    volumes:
      - ./.db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: datapass

    # Workaround to allow data volumes on the current directory on Windows
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON

  wp:
    image: wordpress
    volumes:
      - ./:/var/www/html

      # Disable cache and increase file size limits at the same time
      - ./php-config.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: datapass
